<template>
  <a-card title="Xem điểm">
    <div class="view-score">
      <a-table :columns="columns" size="small" :dataSource="data" v-if="data"> </a-table>
      <a-spin v-else></a-spin>
    </div>
  </a-card>
</template>

<script>
import { useMenuUsers } from '../../../stores/use-menu-users';
export default {
  setup() {
    const store = useMenuUsers();
    store.onSelectedKeys(["users-view-score"]);
    const columns = [
      { title: "STT", dataIndex: "stt", key: "stt", width:20 },
      { title: "Mã môn", dataIndex: "ma_mh", key: "ma_mh", width:90 },
      { title: "Tên môn", dataIndex: "ten_mh", key: "ten_mh" },
      { title: "Quá trình", dataIndex: "diem_qt", key: "diem_qt", width:30 },
      { title: "Giữa kỳ", dataIndex: "diem_gk", key: "diem_gk", width:30 },
      { title: "Điểm thi", dataIndex: "diem_thi", key: "diem_thi", width:30 },
      { title: "Điểm TK", dataIndex: "diem_tk", key: "diem_tk", width:30 },
      { title: "Kết quả", dataIndex: "ketqua", key: "ketqua", width:50 },
    ];
    const data = [
      {
        key: 1,
        stt: 1,
        ma_mh: "GS49004",
        ten_mh: "Thí nghiệm Vật lý_Phần 1",
        diem_qt: 10.0,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 2,
        stt: 2,
        ma_mh: "GS43001",
        ten_mh: "Vật lý 1",
        diem_qt: 10.0,
        diem_gk: 9.0,
        diem_thi: 5.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 3,
        stt: 3,
        ma_mh: "GS33001",
        ten_mh: "Toán A1 (Hàm 1 biến, chuỗi)",
        diem_qt: 10.0,
        diem_gk: 10.0,
        diem_thi: 8.0,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 4,
        stt: 4,
        ma_mh: "GS59002",
        ten_mh: "Thực hành Tin học đại cương",
        diem_qt: null,
        diem_gk: 10.0,
        diem_thi: 9.5,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 5,
        stt: 5,
        ma_mh: "GS19001",
        ten_mh: "Tiếng Anh 1",
        diem_qt: 9.0,
        diem_gk: 7.0,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 6,
        stt: 6,
        ma_mh: "GS59001",
        ten_mh: "Tin học đại cương",
        diem_qt: null,
        diem_gk: 8.0,
        diem_thi: 8.2,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 7,
        stt: 7,
        ma_mh: "CS09001",
        ten_mh: "Nhập môn lập trình",
        diem_qt: 10.0,
        diem_gk: 5.0,
        diem_thi: 6.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 8,
        stt: 8,
        ma_mh: "GS43002",
        ten_mh: "Vật lý 2",
        diem_qt: 10.0,
        diem_gk: 10.0,
        diem_thi: 8.0,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 9,
        stt: 9,
        ma_mh: "GS99001",
        ten_mh: "Giáo dục thể chất 1",
        diem_qt: 8.0,
        diem_gk: null,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 10,
        stt: 10,
        ma_mh: "CS09002",
        ten_mh: "Thực hành Nhập môn lập trình",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 10.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 11,
        stt: 11,
        ma_mh: "GS49005",
        ten_mh: "Thí nghiệm Vật lý_Phần 2",
        diem_qt: 10.0,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 12,
        stt: 12,
        ma_mh: "GS99002",
        ten_mh: "Giáo dục thể chất 2",
        diem_qt: 8.0,
        diem_gk: null,
        diem_thi: 5.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 13,
        stt: 13,
        ma_mh: "CS03001",
        ten_mh: "Kỹ thuật số",
        diem_qt: 10.0,
        diem_gk: 9.5,
        diem_thi: 7.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 14,
        stt: 14,
        ma_mh: "GS19002",
        ten_mh: "Tiếng Anh 2",
        diem_qt: 9.0,
        diem_gk: 8.0,
        diem_thi: 7.6,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 15,
        stt: 15,
        ma_mh: "GS79005",
        ten_mh: "Triết học Mác - Lênin",
        diem_qt: 9.0,
        diem_gk: 5.0,
        diem_thi: 7.8,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 16,
        stt: 16,
        ma_mh: "CS03002",
        ten_mh: "Thí nghiệm Kỹ thuật số",
        diem_qt: 10.0,
        diem_gk: null,
        diem_thi: 10.0,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 17,
        stt: 17,
        ma_mh: "GS33002",
        ten_mh: "Toán A2 (Hàm nhiều biến, giải tích vec tơ)",
        diem_qt: 10.0,
        diem_gk: 10.0,
        diem_thi: 7.5,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 18,
        stt: 18,
        ma_mh: "GS79006",
        ten_mh: "Kinh tế chính trị Mác - Lênin",
        diem_qt: 8.5,
        diem_gk: null,
        diem_thi: 5.3,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 19,
        stt: 19,
        ma_mh: "CS03004",
        ten_mh: "Thực hành Kỹ thuật lập trình",
        diem_qt: null,
        diem_gk: 9.0,
        diem_thi: 10.0,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 20,
        stt: 20,
        ma_mh: "CS09007",
        ten_mh: "Thực hành Nhập môn cấu trúc dữ liệu",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 3.0,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 21,
        stt: 21,
        ma_mh: "GS79007",
        ten_mh: "Chủ nghĩa xã hội khoa học",
        diem_qt: 8.0,
        diem_gk: null,
        diem_thi: 7.3,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 22,
        stt: 22,
        ma_mh: "CS03003",
        ten_mh: "Kỹ thuật lập trình",
        diem_qt: null,
        diem_gk: 9.0,
        diem_thi: 5.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 23,
        stt: 23,
        ma_mh: "CS09006",
        ten_mh: "Tổ chức cấu trúc máy tính",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 3.0,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 24,
        stt: 24,
        ma_mh: "GS33003",
        ten_mh: "Toán A3 (Đại số tuyến tính)",
        diem_qt: 10.0,
        diem_gk: null,
        diem_thi: 10.0,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 25,
        stt: 25,
        ma_mh: "CS09005",
        ten_mh: "Nhập môn cấu trúc dữ liệu",
        diem_qt: 6.5,
        diem_gk: null,
        diem_thi: 6.4,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 26,
        stt: 26,
        ma_mh: "GS29001",
        ten_mh: "Pháp luật Việt Nam đại cương",
        diem_qt: 8.5,
        diem_gk: 7.6,
        diem_thi: 5.3,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 27,
        stt: 27,
        ma_mh: "CS03005",
        ten_mh: "Toán tin học",
        diem_qt: 10.0,
        diem_gk: 6.5,
        diem_thi: 6.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 28,
        stt: 28,
        ma_mh: "GS19003",
        ten_mh: "Tiếng Anh 3",
        diem_qt: 10.0,
        diem_gk: 7.5,
        diem_thi: 7.6,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 29,
        stt: 29,
        ma_mh: "CS03007",
        ten_mh: "Cấu trúc dữ liệu và thuật giải",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 5.5,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 30,
        stt: 30,
        ma_mh: "CS03011",
        ten_mh: "Thực hành Cơ sở dữ liệu",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 31,
        stt: 31,
        ma_mh: "GS19004",
        ten_mh: "Tiếng Anh 4",
        diem_qt: 10.0,
        diem_gk: 7.5,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 32,
        stt: 32,
        ma_mh: "CS03008",
        ten_mh: "Cơ sở dữ liệu",
        diem_qt: 9.0,
        diem_gk: 6.5,
        diem_thi: 6.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 33,
        stt: 33,
        ma_mh: "CS03012",
        ten_mh: "Thực hành Hệ điều hành",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 7.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 34,
        stt: 34,
        ma_mh: "GS79008",
        ten_mh: "Lịch sử Đảng Cộng sản Việt Nam",
        diem_qt: 9.0,
        diem_gk: 8.0,
        diem_thi: 5.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 35,
        stt: 35,
        ma_mh: "CS03009",
        ten_mh: "Hệ điều hành",
        diem_qt: 9.0,
        diem_gk: 6.5,
        diem_thi: 5.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 36,
        stt: 36,
        ma_mh: "CS03047",
        ten_mh: "Nhập môn công tác kỹ sư",
        diem_qt: null,
        diem_gk: 7.5,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 37,
        stt: 37,
        ma_mh: "GS93003",
        ten_mh: "Giáo dục thể chất 3",
        diem_qt: 9.0,
        diem_gk: null,
        diem_thi: 7.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 38,
        stt: 38,
        ma_mh: "CS03010",
        ten_mh: "Thực hành Cấu trúc dữ liệu và thuật giải",
        diem_qt: null,
        diem_gk: 10.0,
        diem_thi: 9.5,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 39,
        stt: 39,
        ma_mh: "CS09008",
        ten_mh: "Thực hành Tổ chức cấu trúc máy tính",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 40,
        stt: 40,
        ma_mh: "GS93004",
        ten_mh: "Giáo dục thể chất 4",
        diem_qt: 9.0,
        diem_gk: null,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 41,
        stt: 41,
        ma_mh: "MI03002",
        ten_mh: "Giáo dục quốc phòng (ĐH)",
        diem_qt: null,
        diem_gk: null,
        diem_thi: 8.4,
        diem_tk: 8.4,
        ketqua: "Đạt",
      },
      {
        key: 42,
        stt: 42,
        ma_mh: "CS03016",
        ten_mh: "Thực hành Lập trình hướng đối tượng",
        diem_qt: null,
        diem_gk: 8.0,
        diem_thi: 1.0,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 43,
        stt: 43,
        ma_mh: "GS79009",
        ten_mh: "Tư tưởng Hồ Chí Minh",
        diem_qt: 8.0,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 44,
        stt: 44,
        ma_mh: "CS03015",
        ten_mh: "Lập trình hướng đối tượng",
        diem_qt: 9.5,
        diem_gk: 8.0,
        diem_thi: 6.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 45,
        stt: 45,
        ma_mh: "CS09009",
        ten_mh: "Mạng máy tính",
        diem_qt: 9.0,
        diem_gk: 7.3,
        diem_thi: 6.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 46,
        stt: 46,
        ma_mh: "CS03014",
        ten_mh: "Đồ án tin học",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 47,
        stt: 47,
        ma_mh: "CS09004",
        ten_mh: "Thực hành Nhập môn Web và ứng dụng",
        diem_qt: null,
        diem_gk: 9.0,
        diem_thi: 6.5,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 48,
        stt: 48,
        ma_mh: "CS03013",
        ten_mh: "Công nghệ phần mềm",
        diem_qt: 9.0,
        diem_gk: 5.0,
        diem_thi: 5.5,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 49,
        stt: 49,
        ma_mh: "CS09003",
        ten_mh: "Nhập môn Web và ứng dụng",
        diem_qt: 10.0,
        diem_gk: 9.0,
        diem_thi: 8.0,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 50,
        stt: 50,
        ma_mh: "CS03017",
        ten_mh: "Lập trình ứng dụng cơ sở dữ liệu",
        diem_qt: null,
        diem_gk: 2.8,
        diem_thi: 8.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 51,
        stt: 51,
        ma_mh: "CS03023",
        ten_mh: "Thương mại điện tử",
        diem_qt: 7.0,
        diem_gk: 5.0,
        diem_thi: 6.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 52,
        stt: 52,
        ma_mh: "CS03020",
        ten_mh: "Quản trị cơ sở dữ liệu",
        diem_qt: 8.0,
        diem_gk: 5.0,
        diem_thi: 5.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 53,
        stt: 53,
        ma_mh: "CS03024",
        ten_mh: "An ninh máy tính",
        diem_qt: 8.5,
        diem_gk: 4.9,
        diem_thi: 7.2,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 54,
        stt: 54,
        ma_mh: "CS03021",
        ten_mh: "Seminar nghề nghiệp",
        diem_qt: null,
        diem_gk: 9.5,
        diem_thi: 10.0,
        diem_tk: 10.0,
        ketqua: "Đạt",
      },
      {
        key: 55,
        stt: 55,
        ma_mh: "CS03025",
        ten_mh: "Thực tập An ninh máy tính",
        diem_qt: null,
        diem_gk: 8.0,
        diem_thi: 8.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 56,
        stt: 56,
        ma_mh: "CS03022",
        ten_mh: "Quản lý dự án",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 6.5,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 57,
        stt: 57,
        ma_mh: "CS03045",
        ten_mh: "Kiểm thử phần mềm",
        diem_qt: 8.5,
        diem_gk: 4.5,
        diem_thi: 5.3,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 58,
        stt: 58,
        ma_mh: "CS03028",
        ten_mh: "Thực hành Lập trình ứng dụng cơ sở dữ liệu",
        diem_qt: null,
        diem_gk: 1.0,
        diem_thi: 10.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 59,
        stt: 59,
        ma_mh: "CS03027",
        ten_mh: "Thực hành Hệ quản trị cơ sơ dữ liệu",
        diem_qt: null,
        diem_gk: 5.0,
        diem_thi: 6.5,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 60,
        stt: 60,
        ma_mh: "CS03030",
        ten_mh: "Đồ án Phân tích thiết kế hệ thống thông tin",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 61,
        stt: 61,
        ma_mh: "CS03038",
        ten_mh: "Lập trình cho thiết bị di động",
        diem_qt: null,
        diem_gk: 5.0,
        diem_thi: 2.0,
        diem_tk: 3.0,
        ketqua: "X",
      },
      {
        key: 62,
        stt: 62,
        ma_mh: "GS09011",
        ten_mh: "Đại cương văn hóa Việt Nam",
        diem_qt: 9.0,
        diem_gk: 9.0,
        diem_thi: 6.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
      {
        key: 63,
        stt: 63,
        ma_mh: "CS03033",
        ten_mh: "Phát triển phần mềm nguồn mở",
        diem_qt: null,
        diem_gk: 6.5,
        diem_thi: 8.3,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 64,
        stt: 64,
        ma_mh: "CS03039",
        ten_mh: "Thực hành Lập trình Web",
        diem_qt: null,
        diem_gk: 10.0,
        diem_thi: 8.5,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 65,
        stt: 65,
        ma_mh: "CS03034",
        ten_mh: "Thực hành Phát triển phần mềm nguồn mở",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 5.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 66,
        stt: 66,
        ma_mh: "CS03041",
        ten_mh: "Thực hành Lập trình cho thiết bị di động",
        diem_qt: null,
        diem_gk: 9.0,
        diem_thi: 8.0,
        diem_tk: 9.0,
        ketqua: "Đạt",
      },
      {
        key: 67,
        stt: 67,
        ma_mh: "CS03029",
        ten_mh: "Đồ án Chuyên ngành",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 6.0,
        diem_tk: 6.0,
        ketqua: "Đạt",
      },
      {
        key: 68,
        stt: 68,
        ma_mh: "CS03036",
        ten_mh: "Lập trình Web",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 4.5,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 69,
        stt: 69,
        ma_mh: "CS09010",
        ten_mh: "Phân tích thiết kế hệ thống thông tin",
        diem_qt: 8.5,
        diem_gk: 5.0,
        diem_thi: 3.5,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 70,
        stt: 70,
        ma_mh: "CS03057",
        ten_mh: "AI cơ bản và ứng dụng",
        diem_qt: null,
        diem_gk: 10.0,
        diem_thi: 6.0,
        diem_tk: 8.0,
        ketqua: "Đạt",
      },
      {
        key: 71,
        stt: 71,
        ma_mh: "CS03043",
        ten_mh: "Xây dựng phần mềm Web",
        diem_qt: null,
        diem_gk: 6.0,
        diem_thi: 4.0,
        diem_tk: 5.0,
        ketqua: "Đạt",
      },
      {
        key: 72,
        stt: 72,
        ma_mh: "CS03042",
        ten_mh: "Triển khai hệ thống thông tin",
        diem_qt: null,
        diem_gk: null,
        diem_thi: null,
        diem_tk: null,
        ketqua: "X",
      },
      {
        key: 73,
        stt: 73,
        ma_mh: "CS03153",
        ten_mh: "Đồ án / Khóa luận tốt nghiệp",
        diem_qt: null,
        diem_gk: null,
        diem_thi: null,
        diem_tk: null,
        ketqua: "X",
      },
      {
        key: 74,
        stt: 74,
        ma_mh: "CS03151",
        ten_mh: "Thực tập tốt nghiệp",
        diem_qt: null,
        diem_gk: 7.0,
        diem_thi: 7.0,
        diem_tk: 7.0,
        ketqua: "Đạt",
      },
    ];

    return {
      columns,
      data,
    };
  },
};
</script>

<style>
.view-score {
  overflow: hidden;
  overflow-x: auto;
}
</style>